### ISSUE TITLE
chore: change logging system

### ISSUE THREAD

**Issue by SoftwrDev** [OhRetro/nakathon#1]
A good thing you could change in your project is instead of using `print` start use the `logging` utility.

**Comment by ohretro** [comment]
I'm already using the logging module at "components/utils/debug.py"
if that's not what you are referring, then what do you mean by that?

The print() is only used to display the results or errors of the Interpreter itself

**Comment by ohretro** [comment]
As we discussed off-line, this issue is no longer necessary because of what I said earlier
